apply plugin: 'com.android.application'

android {
    namespace "com.pitchrec.nativetest"
    compileSdk 36

    defaultConfig {
        applicationId "com.pitchrec.nativetest"
        minSdkVersion 26
        targetSdkVersion 36
        versionCode 1
        versionName "0.1-test"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation('androidx.appcompat:appcompat:1.7.0') {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }
    implementation 'androidx.core:core:1.13.1'
    implementation files('libs/net.sourceforge.lame-3.98.4.jar')
}
